version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2018-04-19T22-54-58Z
    container_name: minio
    volumes:
     - buckets:/data
    ports:
     - "9001:9000"
    environment: ['MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}', 'MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}']
    command: server /data
    networks: ['release-stack']

  setup_minio:
    image: mesosphere/aws-cli:1.14.5
    container_name: setup_minio
    volumes: ['./scripts/setup-minio.sh:/usr/local/bin/setup-minio.sh:ro']
    command: ['/usr/local/bin/setup-minio.sh']
    entrypoint: ['sh']
    environment: ['AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}', 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}']
    networks: ['release-stack']
    depends_on: ['minio']
  
volumes:
  buckets:

networks: {release-stack: {}}